---
# playbook that will install ruby and all app dependencies

- name: add ruby apt repo
  apt_repository: repo='ppa:brightbox/ruby-ng' state=present

- name: install ruby
  apt: name={{ item }} state=installed
  with_items:
    - ruby2.2
    - ruby2.2-dev
    - zlib1g-dev
    - libmysqlclient-dev
    - git

- name: install bundler
  command: gem install bundler

- name: copy code from the repository
  git: repo={{ git_repo }} dest={{ app_directory }}

- name: bundle install
  command: bundle install chdir={{ app_directory }}

